// lib/appFrame.ts
export enum AppFrame {
  HOME = 'HOME',
  CONNECT_WALLET = 'CONNECT_WALLET',
  PLAY_SETUP = 'PLAY_SETUP',
  PLAY_PUZZLE = 'PLAY_PUZZLE',
  FINISH_MINT = 'FINISH_MINT',
  PROFILE_VIEW = 'PROFILE_VIEW',
  HOW_TO_PLAY_VIEW = 'HOW_TO_PLAY_VIEW',
  CHALLENGES_VIEW = 'CHALLENGES_VIEW',
}